---
- name: Create henrylawson.net HTTPD file directory
  file:
    path={{ server_file_root }}/henrylawson.net
    state=directory
    owner=www-hln
    group=www-data
    mode=0750

- name: Create henrylawson.net SSL file directory
  file:
    path={{ server_ssl_root }}/henrylawson.net
    state=directory
    owner=www-hln
    group=www-data
    mode=0750

- name: Copy henrylawson.net SSL Public Certificate
  copy:
    src=ssl/henrylawson.net/2016-03-12/fullchain.pem.gitcrypt
    dest={{ server_ssl_root }}/henrylawson.net/fullchain.pem
    owner=www-admin
    group=www-admin
    mode=0640
  notify:
    - restart nginx

- name: Copy henrylawson.net SSL Private Key
  copy:
    src=ssl/henrylawson.net/2016-03-12/privkey.key.gitcrypt
    dest={{ server_ssl_root }}/henrylawson.net/privkey.pem
    owner=www-admin
    group=www-admin
    mode=0640
  notify:
    - restart nginx

- name: Copy the nginx site configuration file
  template:
    src=henrylawson.net.j2
    dest=/etc/nginx/sites-available/henrylawson.net

- name: Create the link for site enabled specific configurations
  file:
    path=/etc/nginx/sites-enabled/henrylawson.net
    state=link
    src=/etc/nginx/sites-available/henrylawson.net
  notify:
    - restart nginx

