---
- name: Create foinq.com HTTPD file directory
  file:
    path={{ server_file_root }}/foinq.com
    state=directory
    owner=www-fqc
    group=www-data
    mode=0750

- name: Copy foinq.com SSL Public Certificate
  copy:
    src=ssl/foinq.com.crt
    dest={{ server_ssl_root }}/foinq.com.crt
    owner=www-admin
    group=www-admin
    mode=0640
  notify:
    - reload nginx

- name: Copy foinq.com SSL Private Key
  copy:
    src=ssl/foinq.com.key.gitcrypt
    dest={{ server_ssl_root }}/foinq.com.key
    owner=www-admin
    group=www-admin
    mode=0640
  notify:
    - reload nginx

