---
- hosts: all
  sudo: yes
  vars_files:
    - passwords.yml.gitcrypt
  vars:
    server_file_root: /srv/www
    server_ssl_root: /srv/ssl
    server_auth_root: /srv/auth
    server_log_root: /var/log/nginx
    server_conf_root: /etc/nginx
  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes
  roles:
    - role: deploy

# vim:ft=ansible:
