---
- name: Install Apache2
  apt: name=apache2 state=present

- name: Install PHP5
  apt: name=libapache2-mod-php5 state=present
  notify:
    - reload apache

- name: Disable default Virtual Host configuration
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache

- name: Create SSL Root directory
  file: 
    path={{ server_ssl_root }}
    state=directory
  notify:
    - reload apache

- name: Create HTTPD Files Root directory
  file: 
    path={{ server_file_root }}
    state=directory
  notify:
    - reload apache

- name: Create Auth Files Root directory
  file: 
    path={{ server_auth_root }}
    state=directory
  notify:
    - reload apache

- name: Copy SSL Certificate Authorities
  copy:
    src=ssl/{{ item }}.gitcrypt
    dest={{ server_ssl_root }}/{{ item }}
  with_items:
    - startcom.root.ca.pem
    - sub.class1.server.ca.pem
  notify:
    - reload apache

- name: Enable Apache mods
  file:
    src=/etc/apache2/mods-available/{{ item }}
    dest=/etc/apache2/mods-enabled/{{ item }}
    state=link
  with_items:
    - access_compat.load
    - alias.conf
    - alias.load
    - auth_basic.load
    - authn_core.load
    - authn_file.load
    - authz_core.load
    - authz_host.load
    - authz_user.load
    - autoindex.conf
    - autoindex.load
    - deflate.conf
    - deflate.load
    - dir.conf
    - dir.load
    - env.load
    - filter.load
    - mime.conf
    - mime.load
    - negotiation.conf
    - negotiation.load
    - php5.conf
    - php5.load
    - proxy.conf
    - proxy_connect.load
    - proxy_http.load
    - proxy.load
    - rewrite.load
    - setenvif.conf
    - setenvif.load
    - socache_shmcb.load
    - ssl.conf
    - ssl.load
    - status.conf
    - status.load
  notify:
    - reload apache

- name: Copy across _default_:* Virtual Host
  template: 
    src=default.conf.j2
    dest=/etc/apache2/sites-available/default.conf
  notify:
    - reload apache

- name: Enable _default_:* Virtual Host
  file:
    src=/etc/apache2/sites-available/default.conf
    dest=/etc/apache2/sites-enabled/default.conf
    state=link
  notify:
    - reload apache
