---
- name: Install Apache2
  apt: name=apache2 state=present

- name: Disable default Virtual Host configuration
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache

- name: Create SSL Root directory
  file: 
    path={{ server_ssl_root }}
    state=directory
  notify:
    - reload apache

- name: Create HTTPD Files Root directory
  file: 
    path={{ server_file_root }}
    state=directory
  notify:
    - reload apache

- name: Copy SSL Root Certificate Authority
  copy:
    src=ssl/startcom.root.ca.pem.gitcrypt
    dest={{ server_ssl_root }}/startcom.root.ca.pem
  notify:
    - reload apache

- name: Copy SSL Sublcass Certificate Authority
  copy:
    src=ssl/sub.class1.server.ca.pem.gitcrypt
    dest={{ server_ssl_root }}/sub.class1.server.ca.pem
  notify:
    - reload apache