---
- name: Create foinq.com HTTPD file directory
  file: 
    path={{ server_file_root }}/foinq.com
    state=directory
    mode=755

- name: Copy across foinq.com Virtual Host
  template: 
    src=foinq.com.conf.j2
    dest=/etc/apache2/sites-available/foinq.com.conf
  notify:
    - reload apache

- name: Copy foinq.com SSL Public Certificate
  copy: 
    src=ssl/foinq.com.crt
    dest={{ server_ssl_root }}/foinq.com.crt
  notify:
    - reload apache

- name: Copy foinq.com SSL Private Key
  copy: 
    src=ssl/foinq.com.key.gitcrypt
    dest={{ server_ssl_root }}/foinq.com.key
  notify:
    - reload apache

- name: Enable foinq.com Virtual Host
  file:
    src=/etc/apache2/sites-available/foinq.com.conf
    dest=/etc/apache2/sites-enabled/foinq.com.conf
    state=link
  notify:
    - reload apache