---
- name: Clean temporary folder
  shell: rm -rf /tmp/*

- name: Backup books.json file
  command: cp ./app/data/books.json /tmp/books.json.bk
  args:
    chdir: "{{ server_file_root }}/bookeye.foinq.com"
    removes: "{{ server_file_root }}/bookeye.foinq.com/app/data/books.json"

- name: Download latest bookeye.foinq.com code from GitHub
  get_url: 
    url=https://github.com/henrylawson/bookeye-js/archive/master.zip
    dest=/tmp/bookeye-js-master.zip
    force=yes

- name: Extract latest bookeye.foinq.com code
  unarchive: 
    src=/tmp/bookeye-js-master.zip
    dest=/tmp
    copy=no

- name: Stop exisitng bookeye.foinq.com process
  command: forever stopall

- name: Clean bookeye.foinq.com HTTPD folder
  shell: rm -rf {{ server_file_root }}/bookeye.foinq.com/*

- name: Copy henrylawson.net code to HTTPD file directory
  shell: mv /tmp/bookeye-js-master/* {{ server_file_root }}/bookeye.foinq.com

- name: Backup books.json file
  command: cp /tmp/books.json.bk ./app/data/books.json
  args:
    chdir: "{{ server_file_root }}/bookeye.foinq.com"
    removes: /tmp/books.json.bk

- name: Install NPM packages
  command: npm install
  args:
    chdir: "{{ server_file_root }}/bookeye.foinq.com"

- name: Start bookeye.foinq.com process
  command: forever --sourceDir {{ server_file_root }}/bookeye.foinq.com -a -l {{ server_log_root }}/bookeye.foinq.com-forever.log -o {{ server_log_root }}/bookeye.foinq.com-output.log -e {{ server_log_root }}/bookeye.foinq.com-error.log --minUptime 5000 --spinSleepTime 2000 start usain
  args:
    chdir: "{{ server_file_root }}/bookeye.foinq.com"
  notify:
  - reload apache


