---
- name: Install Java
  apt: name=openjdk-8-jre-headless state=present

- name: Clean temporary folder
  shell: rm -rf /tmp/*

- name: Download latest henrylawson.net code from GitHub
  get_url:
    url=https://github.com/henrylawson/henrylawson.net/archive/master.zip
    dest=/tmp/henrylawson.net-master.zip
    force=yes

- name: Extract latest henrylawson.net code
  unarchive:
    src=/tmp/henrylawson.net-master.zip
    dest=/tmp
    copy=no

- name: Install Gems using Bundler
  command: bundle install chdir=/tmp/henrylawson.net-master

- name: Build the Jekyll Site
  command: bundle exec rake build chdir=/tmp/henrylawson.net-master

- name: Clean henrylawson.net HTTPD folder
  shell: rm -rf {{ server_file_root }}/henrylawson.net/*

- name: Copy henrylawson.net code to HTTPD file
  shell: mv /tmp/henrylawson.net-master/_site_deploy/* {{ server_file_root }}/henrylawson.net
  notify:
    - reload apache

- name: Change ownership to the henrylawson.net apache user
  file:
    path="{{ server_file_root }}/henrylawson.net"
    recurse=yes
    owner=wwwhln
    group=wwwdata
