---
- name: Clean temporary folder
  shell: rm -rf /tmp/*

- name: Download latest hen3rz.com code from GitHub
  get_url: 
    url=https://github.com/henrylawson/Hen3rzWebsite/archive/master.zip
    dest=/tmp/Hen3rzWebsite-master.zip
    force=yes

- name: Extract latest hen3rz.com code
  unarchive: 
    src=/tmp/Hen3rzWebsite-master.zip
    dest=/tmp
    copy=no

- name: Clean hen3rz.com HTTPD folder
  shell: rm -rf {{ server_file_root }}/hen3rz.com/*

- name: Copy hen3rz.com code to HTTPD file
  shell: mv /tmp/Hen3rzWebsite-master/* {{ server_file_root }}/hen3rz.com
  notify:
    - reload apache