---
- name: Create hen3rz.com HTTPD file directory
  file: 
    path={{ server_file_root }}/hen3rz.com
    state=directory
    mode=755

- name: Copy across hen3rz.com Virtual Host
  template: 
    src=hen3rz.com.conf.j2
    dest=/etc/apache2/sites-available/hen3rz.com.conf
  notify:
    - reload apache

- name: Enable hen3rz.com Virtual Host
  file:
    src=/etc/apache2/sites-available/hen3rz.com.conf
    dest=/etc/apache2/sites-enabled/hen3rz.com.conf
    state=link
  notify:
    - reload apache

# Deployment

- name: Clean temporary folder
  shell: rm -rf /tmp/*

- name: Download latest hen3rz.com code from GitHub
  get_url: 
    url=https://github.com/henrylawson/Hen3rzWebsite/archive/master.zip
    dest=/tmp/Hen3rzWebsite-master.zip
    force=yes

- name: Extract latest hen3rz.com code
  unarchive: 
    src=/tmp/Hen3rzWebsite-master.zip
    dest=/tmp
    copy=no

- name: Clean hen3rz.com HTTPD folder
  shell: rm -rf {{ server_file_root }}/hen3rz.com/*

- name: Copy hen3rz.com code to HTTPD file
  shell: mv /tmp/Hen3rzWebsite-master/* {{ server_file_root }}/hen3rz.com